webform_product_table.bundle_settings.*.*:
  label: 'Entity bundle settings'
  type: config_object
  mapping:
    enable:
      label: 'Enable'
      type: boolean
    type:
      label: 'Type'
      type: string
    item_category:
      label: 'Item Category'
      type: string
    item_title:
      label: 'Item Title'
      type: string
    item_number:
      label: 'Item Number'
      type: string
    item_description:
      label: 'Item Description'
      type: string
    item_price:
      label: 'Item Price'
      type: string